### PR TITLE
compile with -compat-32

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by mjambon** [comment]
Could you please summarize what the changes do? What's the minimal version of OCaml (wondering about Sys.int_size)?

**Comment by hhugo** [comment]
Sys.word_size was introduced in 4.03. I'll update the PR to lift this restriction.
The change just make sure that bytecode generated on 64bit arch can be executed on 32bit one.
-compat-32 is suppose to checks that constant contained in bytecode will be interpreted the same way regardless of the architecture.

**Comment by mjambon** [comment]
Ok. Thank you for the contribution!

**Comment by mjambon** [comment]
opam release in progress: https://github.com/ocaml/opam-repository/pull/9091

**Pull request merged**
