### PR TITLE
Enable biniou to be safe-string compatible

### PR DESCRIPTION
**Pull request by jpdeplaix**
I'm not sure about changing the type of ```Bi_inbuf.t``` and ```Bi_outbuf.t``` but it seems legit in relation with the rest of the code.

### CODE REVIEW

**Comment by mjambon** [comment]
Thanks for doing this. It looks fine. It shouldn't break too many reverse dependencies; opam's checks this for us now so we'll see.

**Comment by jpdeplaix** [comment]
As I'm doing the same thing for yojson, I'm wondering if letting ```< output : string -> int -> int -> int; .. >``` as is, in the type of ```Bi_outbuf.create_output_writer``` was not a terrible move.
The ```Pervasives.output``` function now takes a ```bytes``` and not a ```string``` :/
For example ```flush_to_channel``` had to be changed a bit and I'm worrying that users might use ```Pervasives.output``` as well.

**Comment by mjambon** [comment]
It comes from here https://github.com/mjambon/biniou/issues/1 and references [this document](http://www.ocaml-programming.de/rec/IO-Classes.html), which hasn't been updated with recommendations for String vs. Bytes.

**Comment by mjambon** [comment]
The opam-repository pull request for biniou 1.1.0 is here: https://github.com/ocaml/opam-repository/pull/9835

**Pull request merged**
